/**
 * Central registry of all event types used in the Redis Pub/Sub system.
 * Add new event types here as the application grows.
 */
const EVENT_TYPES = {
  PROJECT_CREATED: "PROJECT_CREATED",
  PROJECT_UPDATED: "PROJECT_UPDATED",
  PROJECT_DELETED: "PROJECT_DELETED",
  COLLABORATOR_INVITED: "COLLABORATOR_INVITED",
  COLLABORATOR_REMOVED: "COLLABORATOR_REMOVED",
  TASK_ASSIGNED: "TASK_ASSIGNED",
  MESSAGE_SENT: "MESSAGE_SENT",
  MESSAGE_REQUEST_SENT: "MESSAGE_REQUEST_SENT",
  MESSAGE_REQUEST_ACCEPTED: "MESSAGE_REQUEST_ACCEPTED",
  MESSAGE_REQUEST_DECLINED: "MESSAGE_REQUEST_DECLINED",

  // Payment Events
  WALLET_FUNDED: "WALLET_FUNDED",
  WITHDRAWAL_INITIATED: "WITHDRAWAL_INITIATED",
  WITHDRAWAL_COMPLETED: "WITHDRAWAL_COMPLETED",
  WITHDRAWAL_FAILED: "WITHDRAWAL_FAILED",

  // Escrow Events
  ESCROW_PROPOSAL_CREATED: "ESCROW_PROPOSAL_CREATED",
  ESCROW_PROPOSAL_APPROVED: "ESCROW_PROPOSAL_APPROVED",
  ESCROW_FUNDED: "ESCROW_FUNDED",
  MILESTONE_SUBMITTED: "MILESTONE_SUBMITTED",
  MILESTONE_APPROVED: "MILESTONE_APPROVED",
  MILESTONE_DISPUTED: "MILESTONE_DISPUTED",
  ESCROW_PAYMENT_RELEASED: "ESCROW_PAYMENT_RELEASED",
  ESCROW_AUTO_RELEASED: "ESCROW_AUTO_RELEASED",
  MILESTONE_REVIEW_REMINDER: "MILESTONE_REVIEW_REMINDER",

  // Subscription Events
  SUBSCRIPTION_ACTIVATED: "SUBSCRIPTION_ACTIVATED",
  SUBSCRIPTION_CANCELLED: "SUBSCRIPTION_CANCELLED",
  SUBSCRIPTION_RENEWED: "SUBSCRIPTION_RENEWED",
  SUBSCRIPTION_EXPIRED: "SUBSCRIPTION_EXPIRED",
  SUBSCRIPTION_PAST_DUE: "SUBSCRIPTION_PAST_DUE",
};

module.exports = EVENT_TYPES;
