const TASK_STATUS = {
  TODO: "TODO",
  IN_PROGRESS: "IN_PROGRESS",
  COMPLETED: "COMPLETED",
};

const AGREEMENT_STATUS = {
  PENDING: "PENDING",
  SIGNED: "SIGNED",
  ARCHIVED: "ARCHIVED",
};

const PROJECT_VISIBILITY = {
  PUBLIC: "PUBLIC",
  PRIVATE: "PRIVATE",
};

const PROJECT_STATUS = {
  ACTIVE: "ACTIVE",
  COMPLETED: "COMPLETED",
};

const COLLABORATOR_ROLE = {
  OWNER: "OWNER",
  COLLABORATOR: "COLLABORATOR",
};

const NOTIFICATION_TYPE = {
  INVITE: "INVITE",
  SYSTEM: "SYSTEM",
  TASK_ASSIGNED: "TASK_ASSIGNED",
  MESSAGE: "MESSAGE",
};

module.exports = {
  TASK_STATUS,
  AGREEMENT_STATUS,
  PROJECT_VISIBILITY,
  PROJECT_STATUS,
  COLLABORATOR_ROLE,
  NOTIFICATION_TYPE,
};
